# Classical Graham-Schmidt step-by-step in Julia

Illustrate a few steps of Classical Graham Schmidt algorithm in Julia on a random
matrix A, with code roughly following blackboard formulae. This will illustrate basic
linear algebra and matrix-vector operations in Julia, which you can modify and place
into loops to build  a `Q,R = qrcgs(A)` function for arbitrary `A`. 

IAM 961 Numerical Linear Algebra, University of New Hampshire, John Gibson, 2024-10-02

## A couple steps of Classical Graham-Schmidt

Given an $m \times m$ matrix $A$ of full rank, we compute unitary $Q$ and upper-triangular $R$
via

Iterate $j=1, 2, \ldots, m$.
\begin{align*}
   r_{ij} &= q_i^* a_j \quad \text{for } i=1,2,\ldots,j-1 \\
   v_j &= a_j - \sum_{i=1}^{j-1} q_i r_{ij} \\
   r_{jj} &= \|v_j\|_2 \\
   q_j &= v_j/r_{jj}
\end{align*}
where $a_j$ is notation for the $j$th column of $A$, etc. 

### Initialization 

Create random square matrix $A$ and empty $Q,R$ matrices to match.

In [1]:
using LinearAlgebra

A = randn(4,4)

4×4 Matrix{Float64}:
  0.383686  0.917295   -1.38342    -0.119626
  1.72632   0.313792    0.116499    1.46465
 -0.61825   1.21897     0.154344    0.910802
 -0.781526  0.0659566  -0.0347704   0.368184

In [2]:
m,n = size(A)  # in function qrcgs(A), check that m == n
Q = zeros(m,m) 
R = zeros(m,m) 

4×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

### iteration j=1

In [3]:
j=1

vj = A[:,j]       
R[j,j] = norm(vj)

2.0298817719193814

In [4]:
Q[:,j] = vj/R[j,j]

4-element Vector{Float64}:
  0.18901866782866142
  0.8504548927205354
 -0.3045741685313926
 -0.3850103823579199

In [5]:
Q

4×4 Matrix{Float64}:
  0.189019  0.0  0.0  0.0
  0.850455  0.0  0.0  0.0
 -0.304574  0.0  0.0  0.0
 -0.38501   0.0  0.0  0.0

In [6]:
R

4×4 Matrix{Float64}:
 2.02988  0.0  0.0  0.0
 0.0      0.0  0.0  0.0
 0.0      0.0  0.0  0.0
 0.0      0.0  0.0  0.0

### iteration j=2

In [7]:
j=2

aj = A[:,j]

R[1,j] = Q[:,1]' * aj

0.04358986926240915

In [8]:
vj = aj - Q[:,1]*R[1,j]

4-element Vector{Float64}:
 0.9090555752995674
 0.2767211671825934
 1.2322513193270748
 0.08273912816134439

In [9]:
R[j,j] = norm(vj)

1.5582829398611602

In [10]:
qj = vj/R[j,j]

4-element Vector{Float64}:
 0.5833700363687241
 0.17758082316376297
 0.7907750818582829
 0.05309634472974226

In [11]:
Q[:,j] = qj

4-element Vector{Float64}:
 0.5833700363687241
 0.17758082316376297
 0.7907750818582829
 0.05309634472974226

In [12]:
Q

4×4 Matrix{Float64}:
  0.189019  0.58337    0.0  0.0
  0.850455  0.177581   0.0  0.0
 -0.304574  0.790775   0.0  0.0
 -0.38501   0.0530963  0.0  0.0

In [13]:
R

4×4 Matrix{Float64}:
 2.02988  0.0435899  0.0  0.0
 0.0      1.55828    0.0  0.0
 0.0      0.0        0.0  0.0
 0.0      0.0        0.0  0.0

### iteration j = 3

In [14]:
j = 3

aj = A[:,j]
R[1,j] = Q[:,1]'*aj
R[2,j] = Q[:,2]'*aj

vj = aj - Q[:,1]*R[1,j] - Q[:,2]*R[2,j]

R[j,j] = norm(vj)
Q[:,j] = vj/R[j,j]

Q

4×4 Matrix{Float64}:
  0.189019  0.58337    -0.789869   0.0
  0.850455  0.177581    0.331135   0.0
 -0.304574  0.790775    0.512487   0.0
 -0.38501   0.0530963  -0.0617514  0.0

In [15]:
R

4×4 Matrix{Float64}:
 2.02988  0.0435899  -0.196038  0.0
 0.0      1.55828    -0.666155  0.0
 0.0      0.0         1.21255   0.0
 0.0      0.0         0.0       0.0

### iteration j=4

In [16]:
j = 4

aj = A[:,j]
R[1,j] = Q[:,1]'*aj
R[2,j] = Q[:,2]'*aj
R[3,j] = Q[:,3]'*aj
vj = aj - Q[:,1]*R[1,j] - Q[:,2]*R[2,j]  - Q[:,3]*R[3,j]
R[j,j] = norm(vj)
Q[:,j] = vj/R[j,j]

Q

4×4 Matrix{Float64}:
  0.189019  0.58337    -0.789869   -0.00758854
  0.850455  0.177581    0.331135    0.368159
 -0.304574  0.790775    0.512487   -0.138805
 -0.38501   0.0530963  -0.0617514   0.919312

In [17]:
R

4×4 Matrix{Float64}:
 2.02988  0.0435899  -0.196038  0.803845
 0.0      1.55828    -0.666155  0.930096
 0.0      0.0         1.21255   1.02352
 0.0      0.0         0.0       0.752185

### QR is done. Now check results

In [18]:
A

4×4 Matrix{Float64}:
  0.383686  0.917295   -1.38342    -0.119626
  1.72632   0.313792    0.116499    1.46465
 -0.61825   1.21897     0.154344    0.910802
 -0.781526  0.0659566  -0.0347704   0.368184

In [19]:
Q*R

4×4 Matrix{Float64}:
  0.383686  0.917295   -1.38342    -0.119626
  1.72632   0.313792    0.116499    1.46465
 -0.61825   1.21897     0.154344    0.910802
 -0.781526  0.0659566  -0.0347704   0.368184

In [20]:
norm(A-Q*R)

2.466969522362136e-16

In [21]:
Q'*Q

4×4 Matrix{Float64}:
  1.0          -2.29951e-17   3.61734e-17   1.09742e-16
 -2.29951e-17   1.0          -9.43842e-17   2.05105e-16
  3.61734e-17  -9.43842e-17   1.0          -1.68438e-16
  1.09742e-16   2.05105e-16  -1.68438e-16   1.0

In [22]:
norm(I-Q'*Q)

5.103062509757291e-16

In [23]:
# now write a function

"""
Q,R = qrcgs(A) 

   return QR decomposition of square matrix A calculated with classical Gram-Schmidt algorithm

   This is a learn-the-algorithm implementation not meant for serious use. Unoptimized, minimal safety checks.
"""
function qrcgs(A)
    # generalize the above calculation using for loops
    for j = 1:somenumber
        # do stuff
    end
    Q,R  # the return statement
end

qrcgs

In [24]:
? UInt8

search: UInt8 UInt128 uint128"" @uint128_str UInt UInt64 UInt32 UInt16 Cuint



```
UInt8 <: Unsigned
```

8-bit unsigned integer type.


In [25]:
qrcgs(A)

LoadError: UndefVarError: `somenumber` not defined

## Examples of matrix-vector manipulations

In [26]:
A = [10i+j for i in 1:5, j in 1:4] # make a matrox by list comprehension

5×4 Matrix{Int64}:
 11  12  13  14
 21  22  23  24
 31  32  33  34
 41  42  43  44
 51  52  53  54

In [27]:
# get A₂₃ element

A[2,3]

23

In [28]:
# get rows 2 through 4 of 3rd col of A
A[2:4, 3]

3-element Vector{Int64}:
 23
 33
 43

In [29]:
# get 3rd col of A (all rows)
A[:,3]

5-element Vector{Int64}:
 13
 23
 33
 43
 53

In [30]:
# get 3 x 3 principle submatrix of A
A[1:3,1:3]

3×3 Matrix{Int64}:
 11  12  13
 21  22  23
 31  32  33

In [31]:
# make a 2 x 2 matrix of random ints from 0 to 9
# and assign it to the lowermost submatrix of A

B = [rand(Int64) % 10 for i in 1:2, j in 1:2]
A[4:5, 3:4] = B
A

5×4 Matrix{Int64}:
 11  12  13  14
 21  22  23  24
 31  32  33  34
 41  42   6  -4
 51  52   2   6